import { IDS } from './fixtures.mjs'
const S = IDS
const cart = JSON.stringify({ state: { items: Array.from({ length: 7 }, (_, k) => ({ catalog_task_id: S.task(k + 1), added_at: '2026-09-12T08:00:00.000Z' })) }, version: 0 })

export const scenes = [
  // ── guest ──
  { persona: 'guest', name: 'g01-login', url: '/login' },
  { persona: 'guest', name: 'g01-login-keyboard', url: '/login', height: 430, actions: [{ focus: 'input[type=email], input[name=email], input' }], full: false },
  { persona: 'guest', name: 'g02-register', url: '/register' },
  { persona: 'guest', name: 'g02-register-filled', url: '/register', actions: [{ fill: ['input', 'Константинопольская Анна Владимировна'] }] },
  { persona: 'guest', name: 'g03-forgot', url: '/forgot-password' },
  { persona: 'guest', name: 'g04-landing', url: '/about' },

  // ── student ──
  { persona: 'student', name: 's01-dashboard', url: '/student' },
  { persona: 'student', name: 's01-menu', url: '/student', actions: [{ clickSel: 'header button' }, { wait: 500 }], full: false },
  { persona: 'student', name: 's02-my-course', url: '/my-course' },
  { persona: 'student', name: 's03-course', url: `/my-course/${S.group}` },
  { persona: 'student', name: 's04-topic', url: `/my-course/${S.group}/topic/${S.topic(1)}` },
  { persona: 'student', name: 's04-topic-solution', url: `/my-course/${S.group}/topic/${S.topic(1)}`, actions: [{ click: 'Решение ДЗ' }, { wait: 800 }] },
  { persona: 'student', name: 's04-topic-hw', url: `/my-course/${S.group}/topic/${S.topic(1)}`, actions: [{ clickSel: 'button:has-text("Домашнее задание")' }, { wait: 1000 }] },
  { persona: 'student', name: 's04-topic-hw-keyboard', url: `/my-course/${S.group}/topic/${S.topic(1)}`, height: 430, actions: [{ clickSel: 'button:has-text("Домашнее задание")' }, { wait: 800 }, { focus: 'textarea' }], full: false },
  { persona: 'student', name: 's04-topic-theory', url: `/my-course/${S.group}/topic/${S.topic(1)}`, actions: [{ clickSel: 'button:has-text("Теория")' }, { wait: 800 }] },
  { persona: 'student', name: 's05-my-homework-submit', url: '/my-homework', actions: [{ click: 'Сдать' }, { wait: 1500 }] },
  { persona: 'student', name: 's04-topic-test', url: `/my-course/${S.group}/topic/${S.topic(1)}`, actions: [{ clickSel: 'button:has-text("Тест")' }, { wait: 800 }] },
  // board/016: тема ученика с вкладкой «Задачи» — 7 задач к уроку, две второй
  // части, часть уже решена (§162).
  { persona: 'student', name: 's04-topic-tasks', url: `/my-course/${S.group}/topic/${S.topic(1)}`, actions: [{ clickSel: 'button:has-text("Задачи")' }, { wait: 800 }] },
  { persona: 'student', name: 's04-topic2-submitted', url: `/my-course/${S.group}/topic/${S.topic(2)}`, actions: [{ clickSel: 'button:has-text("Домашнее задание")' }, { wait: 800 }] },
  { persona: 'student', name: 's04-topic4-notsubmitted', url: `/my-course/${S.group}/topic/${S.topic(4)}`, actions: [{ clickSel: 'button:has-text("Домашнее задание")' }, { wait: 800 }] },
  { persona: 'student', name: 's04-topic4-upload', url: `/my-course/${S.group}/topic/${S.topic(4)}`, actions: [{ clickSel: 'button:has-text("Домашнее задание")' }, { wait: 800 }, { clickSel: 'button:has-text("Загрузить работу")' }, { wait: 1200 }] },
  { persona: 'student', name: 's04-topic4-upload-keyboard', url: `/my-course/${S.group}/topic/${S.topic(4)}`, height: 430, actions: [{ clickSel: 'button:has-text("Домашнее задание")' }, { wait: 800 }, { clickSel: 'button:has-text("Загрузить работу")' }, { wait: 1000 }, { focus: 'textarea' }], full: false },
  { persona: 'student', name: 's04-topic4-upload-selected', url: `/my-course/${S.group}/topic/${S.topic(4)}`, actions: [{ clickSel: 'button:has-text("Домашнее задание")' }, { wait: 800 }, { clickSel: 'button:has-text("Загрузить работу")' }, { wait: 1500 }, { files: ['photo.png', 'figure.png'] }, { wait: 7000 }] },
  { persona: 'student', name: 's04-topic4-upload-selected-keyboard', url: `/my-course/${S.group}/topic/${S.topic(4)}`, height: 430, actions: [{ clickSel: 'button:has-text("Домашнее задание")' }, { wait: 800 }, { clickSel: 'button:has-text("Загрузить работу")' }, { wait: 1500 }, { files: ['photo.png'] }, { wait: 2000 }, { focus: 'textarea' }], full: false },
  { persona: 'student', name: 's05-my-homework', url: '/my-homework' },
  { persona: 'student', name: 's06-catalog', url: '/catalog' },
  { persona: 'student', name: 's06-catalog-physics', url: '/catalog?subject=physics&exam=ege' },
  { persona: 'student', name: 's06-catalog-section', url: `/catalog/${S.section(1)}?subject=physics&exam=ege` },
  { persona: 'student', name: 's06-catalog-topic', url: `/catalog/${S.section(1)}/topic/${S.ctopic(2)}?subject=physics&exam=ege` },
  { persona: 'student', name: 's06-catalog-task', url: `/catalog/task/${S.task(1)}?subject=physics&exam=ege` },
  { persona: 'student', name: 's07-variants', url: '/student/variants' },
  { persona: 'student', name: 's07-variant-work', url: `/student/variants/${S.myAssignment(1)}` },
  { persona: 'student', name: 's07-variant-work-answer', url: `/student/variants/${S.myAssignment(1)}`, height: 430, actions: [{ focus: 'input[type=text], input:not([type=hidden])' }], full: false },
  { persona: 'student', name: 's07-variant-generate', url: '/student/variants/generate' },
  { persona: 'student', name: 's07-variant-build', url: '/student/variants/build' },
  { persona: 'student', name: 's07-variant-stats', url: '/student/variants/stats' },
  { persona: 'student', name: 's08-progress', url: '/my-progress' },
  { persona: 'student', name: 's09-notifications', url: '/notifications' },
  { persona: 'student', name: 's10-settings', url: '/settings' },
  { persona: 'student', name: 's10-settings-telegram', url: '/settings', actions: [{ clickRole: ['button', 'Уведомления'] }, { wait: 800 }] },

  // ── owner (admin mode) ──
  { persona: 'owner', name: 'o01-admin-now', url: '/admin', actions: [{ clickRole: ['button', 'Сейчас'] }, { wait: 1200 }] },
  { persona: 'owner', name: 'o01-admin-overview', url: '/admin', actions: [{ clickRole: ['button', 'Обзор'] }, { wait: 800 }] },
  { persona: 'owner', name: 'o01-admin-students', url: '/admin', actions: [{ clickRole: ['button', 'Ученики'] }, { wait: 800 }] },
  { persona: 'owner', name: 'o01-admin-learning', url: '/admin', actions: [{ clickRole: ['button', 'Учёба'] }, { wait: 800 }] },
  { persona: 'owner', name: 'o01-admin-site', url: '/admin', actions: [{ clickRole: ['button', 'Сайт'] }, { wait: 800 }] },
  { persona: 'owner', name: 'o01-admin-video', url: '/admin', actions: [{ clickRole: ['button', 'Видео'] }, { wait: 800 }] },
  { persona: 'owner', name: 'o01-admin-staff', url: '/admin', actions: [{ clickRole: ['button', 'Команда'] }, { wait: 800 }] },
  { persona: 'owner', name: 'o01-menu', url: '/admin', actions: [{ clickSel: 'header button' }, { wait: 500 }], full: false },
  { persona: 'owner', name: 'o02-telegram-journal', url: '/admin/telegram' },
  { persona: 'owner', name: 'o03-course-program', url: '/course-program' },
  { persona: 'owner', name: 'o03-course-program-course', url: `/course-program?course=${S.course}`, actions: [{ click: 'Физика ЕГЭ 2027' }, { wait: 1000 }] },
  { persona: 'owner', name: 'o03-course-program-topic', url: `/course-program?course=${S.course}`, actions: [{ click: 'Физика ЕГЭ 2027' }, { wait: 800 }, { click: 'Равноускоренное прямолинейное' }, { wait: 1000 }] },
  { persona: 'owner', name: 'o03-course-program-materials', url: `/course-program?course=${S.course}`, actions: [{ click: 'Физика ЕГЭ 2027' }, { wait: 800 }, { clickSel: 'button:has-text("Материалы")' }, { wait: 1200 }] },
  { persona: 'owner', name: 'o03-course-program-materials-topic', url: `/course-program?course=${S.course}`, actions: [{ click: 'Физика ЕГЭ 2027' }, { wait: 800 }, { clickSel: 'button:has-text("Материалы")' }, { wait: 1000 }, { click: 'Равноускоренное прямолинейное' }, { wait: 1200 }] },
  // board/016: экран преподавателя той же темы — тайл «Задачи» (§162/§164):
  // сколько прикреплено и как решают.
  { persona: 'owner', name: 'o03-course-program-tasks', url: `/course-program?course=${S.course}`, actions: [{ click: 'Физика ЕГЭ 2027' }, { wait: 800 }, { clickSel: 'button:has-text("Материалы")' }, { wait: 1000 }, { click: 'Равноускоренное прямолинейное' }, { wait: 1500 }, { clickSel: '[data-testid="topic-tile-test"]' }, { wait: 1000 }, { eval: '(() => { const el = [...document.querySelectorAll("div")].find(e => /(auto|scroll)/.test(getComputedStyle(e).overflowY) && e.scrollHeight > e.clientHeight + 5); if (el) el.scrollTop = el.scrollHeight })()' }, { wait: 500 }], full: false },
  { persona: 'owner', name: 'o04-catalog', url: '/catalog' },
  { persona: 'owner', name: 'o04-catalog-physics', url: '/catalog?subject=physics&exam=ege' },
  { persona: 'owner', name: 'o04-catalog-section', url: `/catalog/${S.section(1)}?subject=physics&exam=ege` },
  { persona: 'owner', name: 'o04-catalog-topic', url: `/catalog/${S.section(1)}/topic/${S.ctopic(2)}?subject=physics&exam=ege` },
  { persona: 'owner', name: 'o04-catalog-task', url: `/catalog/task/${S.task(1)}?subject=physics&exam=ege` },
  { persona: 'owner', name: 'o04-catalog-task-solution', url: `/catalog/task/${S.task(1)}?subject=physics&exam=ege`, actions: [{ click: 'Решение' }, { wait: 500 }] },
  { persona: 'owner', name: 'o05-cart', url: '/catalog', actions: [{ ls: ['almiron-cart', cart] }, { goto: '/cart' }] },
  { persona: 'owner', name: 'o05-catalog-with-cart', url: `/catalog/${S.section(1)}/topic/${S.ctopic(2)}?subject=physics&exam=ege` },
  { persona: 'owner', name: 'o05-collection', url: `/collections/${S.collection}` },
  { persona: 'owner', name: 'o05-collection-export', url: `/collections/${S.collection}`, actions: [{ click: 'PDF' }, { wait: 800 }] },
  { persona: 'owner', name: 'o06-queue', url: '/homework-queue' },
  { persona: 'owner', name: 'o06-queue-filters', url: '/homework-queue', actions: [{ clickSel: 'text=На доработке' }, { wait: 500 }] },
  { persona: 'owner', name: 'o06-review', url: '/homework-queue', actions: [{ clickSel: 'button:has-text("Проверить")' }, { wait: 2000 }] },
  { persona: 'owner', name: 'o06-review-verdict', url: '/homework-queue', actions: [{ clickSel: 'button:has-text("Проверить")' }, { wait: 2000 }, { eval: '(() => { const el = [...document.querySelectorAll("div")].find(e => /(auto|scroll)/.test(getComputedStyle(e).overflowY) && e.scrollHeight > e.clientHeight + 5); if (el) el.scrollTop = el.scrollHeight })()' }, { wait: 600 }], full: false },
  { persona: 'owner', name: 'o06-review-keyboard', url: '/homework-queue', height: 430, actions: [{ clickSel: 'button:has-text("Проверить")' }, { wait: 2000 }, { focus: 'textarea' }, { wait: 400 }], full: false },
  { persona: 'owner', name: 'o06-review-landscape', url: '/homework-queue', width: 844, height: 390, actions: [{ clickSel: 'button:has-text("Проверить")' }, { wait: 2000 }], full: false },
  { persona: 'owner', name: 'o07-students', url: '/students' },
  { persona: 'owner', name: 'o07-students-invites', url: '/students', actions: [{ clickRole: ['button', 'Приглашения'] }, { wait: 600 }] },
  { persona: 'owner', name: 'o07-students-distribute', url: '/students', actions: [{ clickRole: ['button', 'Новые ученики'] }, { wait: 600 }, { clickRole: ['button', 'Распределить'] }, { wait: 800 }] },
  { persona: 'owner', name: 'o07-student-profile', url: `/students/${S.otherStudent(0)}` },
  { persona: 'owner', name: 'o07-student-journal', url: `/students/${S.otherStudent(0)}/journal` },
  { persona: 'owner', name: 'o08-variants', url: '/variants' },
  { persona: 'owner', name: 'o08-variants-list', url: '/variants/all' },
  { persona: 'owner', name: 'o08-variants-exam', url: '/variants/exam/physics/ege' },
  { persona: 'owner', name: 'o08-variant-assign', url: `/variants/${S.variant(1)}/assign` },
  { persona: 'owner', name: 'o08-variant-assignments', url: `/variants/${S.variant(1)}/assignments` },
  { persona: 'owner', name: 'o08-variant-detail', url: `/variants/${S.variant(1)}` },
  { persona: 'owner', name: 'o08-variant-builder', url: '/variant-builder' },
  { persona: 'owner', name: 'o08-tests', url: '/tests' },
  { persona: 'owner', name: 'o08-test-detail', url: `/tests/${S.test(1)}` },
  { persona: 'owner', name: 'o09-notifications', url: '/notifications' },
  { persona: 'owner', name: 'o10-settings', url: '/settings' },
  { persona: 'owner', name: 'o11-teacher-dashboard', url: '/teacher' },
  { persona: 'owner', name: 'o12-groups', url: `/groups/${S.group}` },

  // ── 360 narrow check on the densest screens ──
  { persona: 'student', name: 's01-dashboard', url: '/student', width: 360, height: 740 },
  { persona: 'student', name: 's04-topic', url: `/my-course/${S.group}/topic/${S.topic(1)}`, width: 360, height: 740 },
  { persona: 'student', name: 's07-variant-work', url: `/student/variants/${S.myAssignment(1)}`, width: 360, height: 740 },
  { persona: 'owner', name: 'o01-admin-now', url: '/admin', width: 360, height: 740, actions: [{ clickRole: ['button', 'Сейчас'] }, { wait: 1200 }] },
  { persona: 'owner', name: 'o04-catalog-section', url: `/catalog/${S.section(1)}?subject=physics&exam=ege`, width: 360, height: 740 },
  { persona: 'owner', name: 'o06-queue', url: '/homework-queue', width: 360, height: 740 },
  { persona: 'owner', name: 'o07-students', url: '/students', width: 360, height: 740 },
]
